checkpoints_dir: /hpcgpfs01/scratch/yhuang2/merged/checkpoints
dataroot: /sdcc/u/yhuang2/PROJs/GAN/datasets/ls4gan/toyzero_cropped/stable_toyzero_1001_500-512x512_U
name: toyzero_512x512_8_16
batch_size: 8
ngf: 16
ndf: 16
n_epochs: 100
save_epoch_freq: 20