checkpoints_dir: /hpcgpfs01/scratch/yhuang2/merged/checkpoints
dataroot: /sdcc/u/yhuang2/PROJs/GAN/datasets/ls4gan/toyzero_cropped/stable_toyzero_1001_500-512x512_U
name: toyzero_512x512_2_64
batch_size: 2
ngf: 64
ndf: 64
n_epochs: 100
save_epoch_freq: 20
